apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-app
spec:
  destination:
    name: ''
    namespace: argocd
    server: 'https://kubernetes.default.svc'
  source:
    path: kube
    repoURL: 'https://github.com/schemmeltobi/elasticsearch-terraform'
    targetRevision: HEAD
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
