apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: eck-operator
  namespace: argocd
spec:
  project: default
  source:
    chart: eck-operator
    repoURL: https://helm.elastic.co
    targetRevision: 2.5.0
    helm:
      releaseName: elastic
      values: |
        managedNamespaces:
         - elastic
        installCRDs: false
  destination:
    server: "https://kubernetes.default.svc"
    namespace: elastic
  syncPolicy:
    syncOptions:
      - CreateNamespace=true  